theme: minima

title: Victoria's blog 
author: Victoria
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My blog post. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
# social links
twitter_username: your-twitter-handle
github_username:  vila89

show_excerpts: true # set to false to remove excerpts on the homepage
